### ISSUE TITLE
大佬，能不能写一个基于deepctrl-sft-data微调的教程，谢谢

### ISSUE THREAD

**Issue by bestlee666** [seanzhang-zhichen/llama3-chinese#4]
大佬，能不能写一个基于deepctrl-sft-data微调的教程，谢谢

**Comment by seanzhang-zhichen** [comment]
> 大佬，能不能写一个基于deepctrl-sft-data微调的教程，谢谢

暂时没时间，你可以使用llama factory试试，这个项目是基于llama factory框架训的
