### ISSUE TITLE
效果差距很大

### ISSUE THREAD

**Issue by icefairy** [seanzhang-zhichen/llama3-chinese#5]
运行环境ollama 4位量化
这是用合并版本的
{"model":"llama3zh","stream":false,"messages":[{"role":"user","content":"你知道抖音出的豆包AI助手吗？"}]}

回复：
{
    "model": "llama3zh",
    "created_at": "2024-04-23T05:59:03.127003916Z",
    "message": {
        "role": "assistant",
        "content": "嗯，我能说出“人”和“事”，但我没法看到您帮忙的AI。"
    },
    "done": true,
    "total_duration": 3451049563,
    "load_duration": 2837478522,
    "prompt_eval_count": 23,
    "prompt_eval_duration": 93932000,
    "eval_count": 24,
    "eval_duration": 386989000
}

原版llama3
{"model":"llama3","stream":false,"messages":[{"role":"user","content":"你知道抖音出的豆包AI助手吗？"}]}

回复：
{
    "model": "llama3",
    "created_at": "2024-04-23T05:58:11.000194875Z",
    "message": {
        "role": "assistant",
        "content": "You're referring to Douyin's (TikTok's) AI assistant called \"豆包\" (dòu bāo) or \"Beanbag\" in English! 😄\n\nYes, I'm familiar with it. Beanbag is an AI-powered chatbot that was introduced by TikTok (formerly Musical.ly) in 2020. It allows users to interact with the platform through natural language processing (NLP), enabling them to perform various tasks, such as:\n\n1. Searching for content: Users can ask Beanbag to find specific videos or hashtags.\n2. Creating new content: Beanbag helps users come up with ideas and even generates captions for their own videos.\n3. Chatting with friends: The AI assistant enables users to engage in conversations with each other within the app.\n\nBeanbag is designed to provide a more intuitive and user-friendly experience for TikTok users, making it easier for them to discover and interact with content on the platform. 💡\n\nHave you tried using Beanbag or any similar AI-powered chatbots? How was your experience? 🤔"
    },
    "done": true,
    "total_duration": 3970390079,
    "load_duration": 617960,
    "prompt_eval_count": 10,
    "prompt_eval_duration": 124831000,
    "eval_count": 221,
    "eval_duration": 3709305000
}

**Comment by seanzhang-zhichen** [comment]
> 运行环境ollama 4位量化 这是用合并版本的 {"model":"llama3zh","stream":false,"messages":[{"role":"user","content":"你知道抖音出的豆包AI助手吗？"}]}
> 
> 回复： { "model": "llama3zh", "created_at": "2024-04-23T05:59:03.127003916Z", "message": { "role": "assistant", "content": "嗯，我能说出“人”和“事”，但我没法看到您帮忙的AI。" }, "done": true, "total_duration": 3451049563, "load_duration": 2837478522, "prompt_eval_count": 23, "prompt_eval_duration": 93932000, "eval_count": 24, "eval_duration": 386989000 }
> 
> 原版llama3 {"model":"llama3","stream":false,"messages":[{"role":"user","content":"你知道抖音出的豆包AI助手吗？"}]}
> 
> 回复： { "model": "llama3", "created_at": "2024-04-23T05:58:11.000194875Z", "message": { "role": "assistant", "content": "You're referring to Douyin's (TikTok's) AI assistant called "豆包" (dòu bāo) or "Beanbag" in English! 😄\n\nYes, I'm familiar with it. Beanbag is an AI-powered chatbot that was introduced by TikTok (formerly Musical.ly) in 2020. It allows users to interact with the platform through natural language processing (NLP), enabling them to perform various tasks, such as:\n\n1. Searching for content: Users can ask Beanbag to find specific videos or hashtags.\n2. Creating new content: Beanbag helps users come up with ideas and even generates captions for their own videos.\n3. Chatting with friends: The AI assistant enables users to engage in conversations with each other within the app.\n\nBeanbag is designed to provide a more intuitive and user-friendly experience for TikTok users, making it easier for them to discover and interact with content on the platform. 💡\n\nHave you tried using Beanbag or any similar AI-powered chatbots? How was your experience? 🤔" }, "done": true, "total_duration": 3970390079, "load_duration": 617960, "prompt_eval_count": 10, "prompt_eval_duration": 124831000, "eval_count": 221, "eval_duration": 3709305000 }

不量化试试呢

**Comment by seanzhang-zhichen** [comment]
> 运行环境ollama 4位量化 这是用合并版本的 {"model":"llama3zh","stream":false,"messages":[{"role":"user","content":"你知道抖音出的豆包AI助手吗？"}]}
> 
> 回复： { "model": "llama3zh", "created_at": "2024-04-23T05:59:03.127003916Z", "message": { "role": "assistant", "content": "嗯，我能说出“人”和“事”，但我没法看到您帮忙的AI。" }, "done": true, "total_duration": 3451049563, "load_duration": 2837478522, "prompt_eval_count": 23, "prompt_eval_duration": 93932000, "eval_count": 24, "eval_duration": 386989000 }
> 
> 原版llama3 {"model":"llama3","stream":false,"messages":[{"role":"user","content":"你知道抖音出的豆包AI助手吗？"}]}
> 
> 回复： { "model": "llama3", "created_at": "2024-04-23T05:58:11.000194875Z", "message": { "role": "assistant", "content": "You're referring to Douyin's (TikTok's) AI assistant called "豆包" (dòu bāo) or "Beanbag" in English! 😄\n\nYes, I'm familiar with it. Beanbag is an AI-powered chatbot that was introduced by TikTok (formerly Musical.ly) in 2020. It allows users to interact with the platform through natural language processing (NLP), enabling them to perform various tasks, such as:\n\n1. Searching for content: Users can ask Beanbag to find specific videos or hashtags.\n2. Creating new content: Beanbag helps users come up with ideas and even generates captions for their own videos.\n3. Chatting with friends: The AI assistant enables users to engage in conversations with each other within the app.\n\nBeanbag is designed to provide a more intuitive and user-friendly experience for TikTok users, making it easier for them to discover and interact with content on the platform. 💡\n\nHave you tried using Beanbag or any similar AI-powered chatbots? How was your experience? 🤔" }, "done": true, "total_duration": 3970390079, "load_duration": 617960, "prompt_eval_count": 10, "prompt_eval_duration": 124831000, "eval_count": 221, "eval_duration": 3709305000 }

这是我不量化，直接使用web推理的结果
