### ISSUE TITLE
微调后的模型batch推理有问题

### ISSUE THREAD

**Issue by orderer0001** [seanzhang-zhichen/llama3-chinese#6]
微调后的模型不能进行batch推理了吗？能run，但是效果不好，除了第一条，后面的结果都是乱码

**Comment by seanzhang-zhichen** [comment]
> 微调后的模型不能进行batch推理了吗？能run，但是效果不好，除了第一条，后面的结果都是乱码

我使用vllm的批量推理是没问题的
